echo "We are trying this practical from linux EC2"
echo "We are from batch-24 and learning git/gihub"
echo "Happy weekend"
echo "ssss"
echo "hkj"
echo "uh;ob"
echo "My name is xyz "
echo "we learning Full stack devlops"
echo "i am trying to don't create merge conflicts"
echo "this scrpit-first"