echo "We are trying this practical from linux EC2"
echo "We are from batch-24 and learning git/gihub"
echo "Happy weekend"
echo "ssss"
echo "hkj"
echo "uh;ob"
echo "move to matheran"
echo "no move to lonavala"
echo "Hi this hotfix1 file"
echo "this scrpit 1"